name: Deploy Backend to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            
              set -e
              
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

              
                cd /home/ubuntu/chessables/backend_1
              
                echo "Node:"
                node -v
                npm -v
              
                echo "Pulling code"
                git pull origin main
              
                echo "Installing deps"
                npm ci
              
                echo "Generating Prisma client"
                cd src
                npx prisma generate
                
                cd ..
              
                echo "Building TypeScript"
                tsc -b tsconfig.json
              
                echo "Reloading app"
                pm2 reload index
